### ISSUE TITLE
Optimize for other form factors

### ISSUE THREAD

**Issue by valkriaine** [valkriaine/Factor_Launcher_Reboot#4]

**Comment by Valkriaine** [comment]
"When horizontal, simply lay out the two screens (start/app list) together, each taking up half the screen. That would work perfectly, I believe, without taking away the feeling of Windows Phone 7."

**Comment by Valkriaine** [comment]
Tablet, duo screen, foldable

**Comment by valkriaine** [comment]
This won't be worked on until basic features are finished.
