### ISSUE TITLE
App list disappeared

### ISSUE THREAD

**Issue by loic5032** [Valkriaine/Factor_Launcher_Reboot#56]
I installed the launcher yesterday evening on my sony xperia 10 with android 11 (LineageOS). When I turned on the phone this morning, the app list was empty. [Screenshot](https://photos.app.goo.gl/qcwGvQdEXRuoB35Y6)

**Comment by ssilko** [comment]
Same problem on my Xiaomi with last update

**Comment by Valkriaine** [comment]
Thanks for the feedback! I will fix it as soon as possible

**Comment by Valkriaine** [comment]
> I installed the launcher yesterday evening on my sony xperia 10 with android 11 (LineageOS). When I turned on the phone this morning, the app list was empty. [Screenshot](https://photos.app.goo.gl/qcwGvQdEXRuoB35Y6)

Hello! I pushed a new update to the Play Store, and it should be available in a couple hours. If the new update still displays empty app drawer unfortunately you'll have to reset the app. Sorry for the inconvenience but clearing app storage is the only way as somehow it messed with the database :(

**Comment by Valkriaine** [comment]
Temporarily closed until future occurrence
